# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            McNami
tagline:          "/x/"
description:      "don't try"
url:              https://x.mcnami.com
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           "Dim McNami"
  url:            https://twitter.com/dimmcnami

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            3.6.0
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             

twitter: https://twitter.com/dimmcnami

medium: https://medium.com/@dimmcnami

linkedin: https://linkedin.com/in/mcnami

gmail: hello+x@mcnami.com

dribbble: https://dribbble.com/dimmcnami

instagram: https://instagram.com/dimmcnami

